name: release

on:
  release:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install upload deps
        run: pip install '.[upload]'

      - name: Run pre-commit
        run: |
          python -m build
          twine upload dist/*
